name: Android CI/CD

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Setup Gradle
      run: |
        ls -la
        echo "Current directory: $(pwd)"
        echo "Checking gradlew file..."
        file gradlew
        head -5 gradlew
        chmod +x gradlew
        ls -la gradlew
        if ./gradlew --version; then
          echo "Gradle wrapper works!"
        else
          echo "Gradle wrapper failed, using gradle command..."
          gradle --version
        fi

    - name: Build with Gradle
      run: |
<<<<<<< Updated upstream
        if ./gradlew clean; then
          ./gradlew assembleDebug --stacktrace --info
        else
          echo "Using gradle command instead..."
          gradle clean
          gradle assembleDebug --stacktrace --info
=======
        echo "=== Build Environment ==="
        java -version
        echo "=== Gradle Version ==="
        if ./gradlew --version; then
          echo "=== Starting Build ==="
          ./gradlew clean
          ./gradlew assembleDebug --stacktrace --info --warning-mode all
        else
          echo "=== Using Gradle Command ==="
          gradle clean
          gradle assembleDebug --stacktrace --info --warning-mode all
>>>>>>> Stashed changes
        fi

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/app-debug.apk

    - name: Create Release
      if: github.ref == 'refs/heads/main'
      uses: softprops/action-gh-release@v1
      with:
        files: app/build/outputs/apk/debug/app-debug.apk
        tag_name: v1.1.0
        name: Ad Blocker VPN v1.1.0 - Fixed Version
        body: |
          ## 🚀 Ad Blocker VPN v1.1.0
          
          ### ✅ Fixed Issues:
          - **VPN Startup Issues** - Fixed VPN interface establishment
          - **Status Display** - Now shows correct VPN connection status
          - **Error Handling** - Proper error messages and recovery
          - **Service Stability** - Improved VPN service lifecycle
          
          ### 🔧 New Features:
          - **Test Connection** button to verify VPN functionality
          - **Improved UI** with better status updates
          - **Enhanced ad domain list** including Facebook, YouTube, Instagram ads
          - **Better error handling** and service stability
          
          ### 📱 Installation Instructions:
          1. **Download** the APK file below
          2. **Enable** "Install from Unknown Sources" in Android Settings
          3. **Install** the APK file
          4. **Grant VPN permission** when prompted
          5. **Start VPN** and begin blocking ads!
          
          ### 🎯 How to Test:
          1. Start VPN in the app
          2. Open any app with ads (YouTube, Facebook, etc.)
          3. Watch the "Ads Blocked" counter increase
          4. Use "Test Connection" button to verify internet works
          
          ### ⚠️ Important Notes:
          - **Cannot be published** on Google Play Store (ad-blocking policy)
          - **Test on physical device** (VPN doesn't work on emulator)
          - **Requires Android 5.0+** (API 21+)
          - **Internet will work normally** - only ads are blocked
          
          ### 🔍 Technical Details:
          - **Language**: Kotlin
          - **Architecture**: Service-based VPN with UI updates
          - **Dependencies**: AndroidX, Material Design
          - **Min SDK**: API 21 (Android 5.0+)
          
          ### 🐛 Bug Fixes:
          - Fixed VPN service startup and interface establishment
          - Improved status validation and UI updates
          - Enhanced error handling with proper user feedback
          - Added delayed success message to ensure VPN actually starts
          
          ---
          
          **Note**: This app is for educational purposes. Always respect website terms of service and local regulations.
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
